[package]
name = "format1"
version = "0.1.0"
edition = "2018"
author =["leikang <1013626230@qq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
