[package]
name = "hyperurl"
author = []
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#依赖包项
[dependencies]
tera = "1"
serde = "1"
serde_derive = "1"
lazy_static = "1.2"


